services:
  stock-bot:
    build: .
    container_name: discord-stock-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - FINANCIAL_DATASETS_API_KEY=${FINANCIAL_DATASETS_API_KEY}